using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class V6DwhBookingsOracleNVia
    {
        public string? OrderNumber { get; set; }
        public string? PoNumber { get; set; }
        public DateTime? TransDate { get; set; }
        public DateTime? TransDateWeekEnding { get; set; }
        public string? TransDateWeekNum { get; set; }
        public string? TransDateYearQuarter { get; set; }
        public string? TransDatePeriodName { get; set; }
        public string? ViasPartNumber { get; set; }
        public string? ViasEndCustomer { get; set; }
        public string? InventoryItem { get; set; }
        public string? InventoryItemDesc { get; set; }
        public string? CatalogPartNumber { get; set; }
        public string? OrderLineNumber { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? SchedShipDate { get; set; }
        public double? CcUnitSellingPrice { get; set; }
        public string? OrderHoldStatus { get; set; }
        public double? CcAmtGrossBookings { get; set; }
        public double? TtlOrderVal { get; set; }
        public string? CcCurrency { get; set; }
        public string? OrderLineType { get; set; }
        public decimal? CcExchangeRate { get; set; }
        public DateTime? OrderPromDate { get; set; }
        public string? BilltoId { get; set; }
        public string? BilltoName { get; set; }
        public string? BilltoAddr1 { get; set; }
        public string? BilltoAddr2 { get; set; }
        public string? BilltoAddr3 { get; set; }
        public string? BilltoAddr4 { get; set; }
        public string? BilltoState { get; set; }
        public string? BilltoCity { get; set; }
        public string? BilltoZip { get; set; }
        public string? BilltoCountry { get; set; }
        public string? BilltoCountryDesc { get; set; }
        public string? ShiptoId { get; set; }
        public string? ShiptoName { get; set; }
        public string? ShiptoAddr1 { get; set; }
        public string? ShiptoAddr2 { get; set; }
        public string? ShiptoAddr3 { get; set; }
        public string? ShiptoAddr4 { get; set; }
        public string? ShiptoState { get; set; }
        public string? ShiptoCity { get; set; }
        public string? ShiptoZip { get; set; }
        public string? ShiptoCountry { get; set; }
        public string? SoldtoId { get; set; }
        public string? SoldtoName { get; set; }
        public string? SoldtoAddr1 { get; set; }
        public string? SoldtoAddr2 { get; set; }
        public string? SoldtoAddr3 { get; set; }
        public string? SoldtoAddr4 { get; set; }
        public string? SoldtoState { get; set; }
        public string? SoldtoCity { get; set; }
        public string? SoldtoZip { get; set; }
        public string? SoldtoCountry { get; set; }
        public string? DataSource { get; set; }
        public DateTime? LineBookedDate { get; set; }
        public DateTime? ActualShipmentDate { get; set; }
        public string? SourceSystemId { get; set; }
        public string? ArInvoiceNumber { get; set; }
        public string? WaybillNumber { get; set; }
        public double? QuantityShipped { get; set; }
        public string? FreightCarrierCode { get; set; }
        public string? SalesRepName { get; set; }
        public string? OaState { get; set; }
        public string? District { get; set; }
        public string? SubRegion { get; set; }
        public string? Region { get; set; }
        public string? SubDistrict { get; set; }
        public string? L2MarketSegment { get; set; }
        public string? L3BusinessGroup { get; set; }
        public string? L4Edw { get; set; }
        public string? L4BusinessUnit { get; set; }
        public string? L45 { get; set; }
        public string? L5ProductLine { get; set; }
        public string? L6ProductFamily { get; set; }
        public string? GlProdLineCode { get; set; }
        public string? GlProdLineDesc { get; set; }
        public string? EndCustomerName { get; set; }
        public string? EndCustomerNumber { get; set; }
        public string? EndCustomerType { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerNumber { get; set; }
        public string? CustomerType { get; set; }
        public string? CustomerClass { get; set; }
        public string? EndCustomerClass { get; set; }
        public string? ViasClientCode { get; set; }
        public string? ViasSalesRepNo { get; set; }
        public string? GlAccount { get; set; }
        public string? GlAccountDesc { get; set; }
        public string? ViasMajorCustomer { get; set; }
        public string? SalesCommissionsKey { get; set; }
        public double? CcUnitListPrice { get; set; }
        public double? QuantityGrossBookings { get; set; }
        public double? CcAmtGlAcctBalActCogs { get; set; }
        public double? CcAmtGlAcctBalActRev { get; set; }
        public double? QuantityOrdered { get; set; }
        public string? ViasLocalCurrencyCode { get; set; }
        public string? Eid { get; set; }
        public string? ShipmentPriority { get; set; }
        public string? SalesRepNumber { get; set; }
        public string? SourceType { get; set; }
        public string? EndCustClass { get; set; }
        public string? EndCustomerSector { get; set; }
        public string? ContractorEndCustomer { get; set; }
    }
}
